#!/system/bin/sh
pwd=$(pwd)
#====================
#
#    Lozano Martínez Run add
#     https://github.com/m1r47/Harpy
#        contribución lala11 para los paracos siempre 
#
#====================
# Colores oscuros
negro="\e[1;30m"
verde="\e[1;32m"
cian="\e[1;36m"
rojo="\e[1;31m"
purpura="\e[1;35m"
amarillo="\e[1;33m"
negro='\033[0;30m'
blanco='\033[1;37m'
#-----------------------------------------
#-----------------------------------------
home=/data/data/com.termux/files/home/
installl=/data/data/com.termux/files/home/Harpy/tools/instalacion/
remover=/data/data/com.termux/files/home/Harpy/tools/remover/
reinstall=/data/data/com.termux/files/home/Harpy/tools/reinstalacion/
update=Harpy/update.sh
rmtools=Harpy/remove.sh
menu=/data/data/com.termux/files/home/Harpy/implement/menu.sh
baner=/data/data/com.termux/files/home/Harpy/implement/baners
#------------------------------------------------------------
if [[ "$1" == "remove" && "$2" == "Nexphisher" ]]; then
	source ${remover}Nexphisher.sh
elif [[ "$1" == "remove" && "$2" == "Ubuntu" ]]; then
  source ${remover}Ubuntu.sh
elif [[ "$1" == "remove" && "$2" == "Root" ]]; then
  source ${remover}Root.sh
elif [[ "$1" == "remove" && "$2" == "DDOS" ]]; then
  source ${remover}DDOS.sh
elif [[ "$1" == "remove" && "$2" == "Doxxer-Toolkit" ]]; then
  source ${remover}Doxxer-Toolkit.sh
elif [[ "$1" == "remove" && "$2" == "ngrok" ]]; then
  source ${remover}ngrok.sh
elif [[ "$1" == "remove" && "$2" == "routersploit" ]]; then
  source ${remover}routersploit.sh
elif [[ "$1" == "remove" && "$2" == "termux-style" ]]; then
  source ${remover}termux-style.sh
elif [[ "$1" == "remove" && "$2" == "torServer" ]]; then
  source ${remover}torServer.sh
elif [[ "$1" == "remove" && "$2" == "Fake-SMS" ]]; then
  source ${remover}Fake-SMS.sh
elif [[ "$1" == "remove" && "$2" == "AdminHack" ]]; then
  source ${remover}AdminHack.sh
elif [[ "$1" == "remove" && "$2" == "slowloris" ]]; then
  source ${remover}slowloris.sh
elif [[ "$1" == "remove" && "$2" == "speedtest" ]]; then
  source ${remover}speedtest.sh
elif [[ "$1" == "remove" && "$2" == "virustotal" ]]; then
  source ${remover}virustotal.sh
elif [[ "$1" == "remove" && "$2" == "translate" ]]; then
  source ${remover}translate.sh
elif [[ "$1" == "remove" && "$2" == "netcat" ]]; then
  source ${remover}netcat.sh
#------------------------------------------------------------
elif [[ "$1" == "install" && "$2" == "netcat" ]]; then
  source ${installl}netcat.sh
elif [[ "$1" == "install" && "$2" == "slowloris" ]]; then
  source ${installl}slowloris.sh
elif [[ "$1" == "install" && "$2" == "translate" ]]; then
  source ${installl}translate.sh
elif [[ "$1" == "install" && "$2" == "virustotal" ]]; then
  source ${installl}virustotal.sh
elif [[ "$1" == "install" && "$2" == "speedtest" ]]; then
  source ${installl}speedtest.sh
elif [[ "$1" == "install" && "$2" == "Nexphisher" ]]; then
  source ${installl}Nexphisher.sh
elif [[ "$1" == "install" && "$2" == "Ubuntu" ]]; then
  source ${installl}Ubuntu.sh
elif [[ "$1" == "install" && "$2" == "Root" ]]; then
  source ${installl}Root.sh
elif [[ "$1" == "install" && "$2" == "DDOS" ]]; then
  source ${installl}DDOS.sh
elif [[ "$1" == "install" && "$2" == "Doxxer-Toolkit" ]]; then
  source ${installl}Doxxer-Toolkit.sh
elif [[ "$1" == "install" && "$2" == "ngrok" ]]; then
  source ${installl}ngrok.sh
elif [[ "$1" == "install" && "$2" == "routersploit" ]]; then
  source ${installl}routersploit.sh
elif [[ "$1" == "install" && "$2" == "termux-style" ]]; then
  source ${installl}termux-style.sh
elif [[ "$1" == "install" && "$2" == "torServer" ]]; then
  source ${installl}torServer.sh
elif [[ "$1" == "install" && "$2" == "Fake-SMS" ]]; then
  source ${installl}Fake-SMS.sh
elif [[ "$1" == "install" && "$2" == "AdminHack" ]]; then
  source ${installl}AdminHack.sh
#------------------------------------------------------------
elif [[ "$1" == "reinstall" && "$2" == "netcat" ]]; then
  source ${reinstall}netcat.sh
elif [[ "$1" == "reinstall" && "$2" == "translate" ]]; then
  source ${reinstall}translate.sh
elif [[ "$1" == "reinstall" && "$2" == "Nexphisher" ]]; then
  source ${reinstall}Nexphisher.sh
elif [[ "$1" == "reinstall" && "$2" == "speedtest" ]]; then
  source ${reinstall}speedtest.sh
elif [[ "$1" == "reinstall" && "$2" == "slowloris" ]]; then
  source ${reinstall}slowloris.sh
elif [[ "$1" == "reinstall" && "$2" == "Ubuntu" ]]; then
  source ${reinstall}Ubuntu.sh
elif [[ "$1" == "reinstall" && "$2" == "Root" ]]; then
  source ${reinstall}Root.sh
elif [[ "$1" == "reinstall" && "$2" == "DDOS" ]]; then
  source ${reinstall}DDOS.sh
elif [[ "$1" == "reinstall" && "$2" == "Doxxer-Toolkit" ]]; then
  source ${reinstall}Doxxer-Toolkit.sh
elif [[ "$1" == "reinstall" && "$2" == "ngrok" ]]; then
  source ${reinstall}ngrok.sh
elif [[ "$1" == "reinstall" && "$2" == "routersploit" ]]; then
  source ${reinstall}routersploit.sh
elif [[ "$1" == "reinstall" && "$2" == "termux-style" ]]; then
  source ${reinstall}termux-style.sh
elif [[ "$1" == "reinstall" && "$2" == "torServer" ]]; then
  source ${reinstall}torServer.sh
elif [[ "$1" == "reinstall" && "$2" == "Fake-SMS" ]]; then
  source ${reinstall}Fake-SMS.sh
elif [[ "$1" == "reinstall" && "$2" == "AdminHack" ]]; then
  source ${reinstall}AdminHack.sh
elif [[ "$1" == "reinstall" && "$2" == "virustotal" ]]; then
  source ${reinstall}virustotal.sh
#----------------------------
elif [[ "$1" == "help" ]]; then
echo -e "$rojo add list $blanco listar herramientas " && sleep 0.1 && echo -e "$rojo add update $blanco actualiza las herramienta " && sleep 0.1
echo -e "$rojo add install $blanco instala la herramienta " && sleep 0.1
echo -e "$rojo add remove $blanco elimina la herramienta " && sleep 0.1 && echo -e "$rojo add reinstall $blanco reinstalar la herramienta" && sleep 0.1
echo -e "$rojo add soport $blanco telegram del desarrollador " && sleep 0.1 && echo -e "$rojo add kill $blanco elimina Harpy y las ${verde} herramientas" && sleep 0.1
#----------------------------
elif [[ "$1" == "list" ]]; then
source ${menu}
##------------------------------------------------------------
elif [[ "$1" == "localhost" ]]; then
ipvt=$(ifconfig | grep -i "inet 192.168" | cut -d " " -f 10)
echo -e "${rojo}[${blanco}+${rojo}]${verde} ${ipvt}"
#----------------------------
elif [[ "$1" == "soport" ]]; then
echo -e "${rojo}[${blanco}+${rojo}]${blanco} Opening support contacts"
termux-open-url https://t.me/s_limk
#----------------------------
elif [[ "$1" == "kill" ]]; then
echo repare
#------------------------------------------------------------
elif [[ "$1" == "update" ]]; then
cd $HOME/Harpy
git pull origin main > /dev/null 2>&1
source update.sh
cd ${pwd}
#----------------------------
else
  echo -e "$blanco[${rojo}+$blanco] operación invalida prueba con${verde} add help "
  exit 1
fi